### ISSUE TITLE
No suitable constructor found for UserUpdateRequest(boolean,boolean)

### ISSUE THREAD

**Issue by morellan** [intercom/intercom-cordova#180]
## Version info
  - Intercom for Cordova/PhoneGap version: intercom-cordova@3.2.0 - phonegap@6.5.0
  - iOS/Android OS version: 6.0
  - iOS/Android Device: Motorola G

## Expected behavior
Successful build (works with intercom-cordova@3.1.3)

## Actual behavior
Build failed

## Steps to reproduce
 1. cordova platform add android
 2. cordova plugin add cordova-plugin-intercom@3.2.0
 3. cordova build android

(I tried to find the UserUpdateRequest source to help fix this but didn't find it, where is it?)

## Logs

```
Error: /Users/mob/Dev/garoo/armin-app/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/app/platforms/android/src/io/intercom/android/sdk/IntercomBridge.java:42: error: no suitable constructor found for UserUpdateRequest(boolean,boolean)
                    Injector.get().getApi().updateUser(new UserUpdateRequest(true, false));
                                                       ^
    constructor UserUpdateRequest.UserUpdateRequest() is not applicable
      (actual and formal argument lists differ in length)
    constructor UserUpdateRequest.UserUpdateRequest(boolean,boolean,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor UserUpdateRequest.UserUpdateRequest(boolean,boolean,Map<String,Object>,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor UserUpdateRequest.UserUpdateRequest(boolean,boolean,Map<String,Object>,int,boolean) is not applicable
      (actual and formal argument lists differ in length)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /app/platforms/android/src/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
```

**Comment by jtreanor** [comment]
Hi @morellan,

Thanks for reporting this. It was caused by an oversight when release version 3.2.1 of our Android Messenger yesterday.

The issue has now been fixed in [3.2.1](https://github.com/intercom/intercom-cordova/releases/tag/3.2.1).

**Comment by morellan** [comment]
Thanks for the quick fix!
